/**
 * KRONOS - File Writer
 * Üretilen içerikleri organize edilmiş dosyalara kaydet
 */

import fs from 'fs-extra';
import path from 'path';
import { ContentPlatform, ReleaseData } from '../types/index.js';

const FILE_NAMES: Record<ContentPlatform, string> = {
  changelog: 'CHANGELOG.md',
  twitter: 'twitter-thread.md',
  linkedin: 'linkedin-post.md',
  producthunt: 'producthunt-launch.md',
  youtube: 'youtube-script.md',
  email: 'email-newsletter.md'
};

const FILE_HEADERS: Record<ContentPlatform, string> = {
  changelog: '# Changelog',
  twitter: '# 🐦 Twitter/X Thread',
  linkedin: '# 💼 LinkedIn Post',
  producthunt: '# 🚀 Product Hunt Launch',
  youtube: '# 🎥 YouTube Video Script',
  email: '# 📧 Email Newsletter'
};

export class FileWriter {
  private outputDir: string;

  constructor(outputDir: string) {
    this.outputDir = outputDir;
  }

  /**
   * Tüm üretilen içerikleri organize şekilde kaydet
   */
  async saveAll(
    content: Map<ContentPlatform, string>,
    data: ReleaseData
  ): Promise<string[]> {
    // Release klasörü oluştur
    const releaseDir = path.join(this.outputDir, `release-${data.version}`);
    await fs.ensureDir(releaseDir);

    const savedFiles: string[] = [];

    // Her içeriği ilgili dosyaya kaydet
    for (const [platform, text] of content.entries()) {
      const filePath = await this.saveContent(releaseDir, platform, text, data);
      savedFiles.push(filePath);
    }

    // Özet dosyası oluştur
    const summaryPath = await this.saveSummary(releaseDir, data, savedFiles);
    savedFiles.push(summaryPath);

    return savedFiles;
  }

  /**
   * Tek bir içeriği kaydet
   */
  private async saveContent(
    releaseDir: string,
    platform: ContentPlatform,
    content: string,
    data: ReleaseData
  ): Promise<string> {
    const filePath = path.join(releaseDir, FILE_NAMES[platform]);
    
    const header = `${FILE_HEADERS[platform]}

> Generated by KRONOS ⌛ for ${data.repoName} v${data.version}
> ${new Date().toISOString()}

---

`;

    // Changelog farklı davranır - üzerine ekler
    if (platform === 'changelog') {
      await this.appendToChangelog(filePath, content, data);
    } else {
      await fs.writeFile(filePath, header + content, 'utf-8');
    }

    return filePath;
  }

  /**
   * Changelog'a yeni sürümü ekle (üzerine yazma, prepend)
   */
  private async appendToChangelog(
    filePath: string,
    newContent: string,
    data: ReleaseData
  ): Promise<void> {
    let existing = '';
    
    if (await fs.pathExists(filePath)) {
      existing = await fs.readFile(filePath, 'utf-8');
    } else {
      existing = `# Changelog

All notable changes to this project will be documented in this file.
The format is based on [Keep a Changelog](https://keepachangelog.com/).

`;
    }

    const versionEntry = `## [${data.version}] - ${new Date().toISOString().split('T')[0]}

${newContent}

`;

    // Başlık sonrasına yeni sürümü ekle
    const lines = existing.split('\n');
    const insertIndex = lines.findIndex(line => line.startsWith('## ')) || 5;
    
    lines.splice(insertIndex, 0, versionEntry);
    
    await fs.writeFile(filePath, lines.join('\n'), 'utf-8');
  }

  /**
   * Özet/index dosyası oluştur
   */
  private async saveSummary(
    releaseDir: string,
    data: ReleaseData,
    files: string[]
  ): Promise<string> {
    const summaryPath = path.join(releaseDir, 'README.md');
    
    const fileList = files
      .map(f => `- [${path.basename(f)}](./${path.basename(f)})`)
      .join('\n');

    const content = `# ⌛ Release ${data.version}

**Project:** ${data.repoName}  
**Released:** ${new Date().toISOString().split('T')[0]}  
**Commits:** ${data.commits.length}  
**Contributors:** ${data.contributors.join(', ')}

## 📦 Generated Content

${fileList}

## 📊 Release Stats

- Total commits: ${data.commits.length}
- Features: ${data.commits.filter(c => c.type === 'feat').length}
- Bug fixes: ${data.commits.filter(c => c.type === 'fix').length}
- Breaking changes: ${data.commits.filter(c => c.type === 'breaking').length}

---

*Generated with KRONOS ⌛ - Time to ship*
`;

    await fs.writeFile(summaryPath, content, 'utf-8');
    return summaryPath;
  }
}
